version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dashboard-backend
    restart: unless-stopped
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"

      # PROD
      - "traefik.http.routers.dashboard-backend-prod.rule=Host(`dashboard-dtn.maisonsetcites.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.dashboard-backend-prod.entrypoints=https"
      - "traefik.http.routers.dashboard-backend-prod.tls=true"

      # TEST
      - "traefik.http.routers.dashboard-backend-test.rule=Host(`dashboard-dtn-t.maisonsetcites.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.dashboard-backend-test.entrypoints=https"
      - "traefik.http.routers.dashboard-backend-test.tls=true"

      # Service commun
      - "traefik.http.services.dashboard-backend.loadbalancer.server.port=8080"

      # Strip /api
      - "traefik.http.middlewares.dashboard-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.dashboard-backend-prod.middlewares=dashboard-backend-stripprefix@docker"
      - "traefik.http.routers.dashboard-backend-test.middlewares=dashboard-backend-stripprefix@docker"


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
      target: runner
    container_name: dashboard-frontend
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"

      # PROD
      - "traefik.http.routers.dashboard-frontend-prod.rule=Host(`dashboard-dtn.maisonsetcites.fr`)"
      - "traefik.http.routers.dashboard-frontend-prod.entrypoints=https"
      - "traefik.http.routers.dashboard-frontend-prod.tls=true"

      # TEST
      - "traefik.http.routers.dashboard-frontend-test.rule=Host(`dashboard-dtn-t.maisonsetcites.fr`)"
      - "traefik.http.routers.dashboard-frontend-test.entrypoints=https"
      - "traefik.http.routers.dashboard-frontend-test.tls=true"

      # Service
      - "traefik.http.services.dashboard-frontend.loadbalancer.server.port=3000"


networks:
  coolify:
    external: true