version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dashboard-backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`dashboard-dtn.maisonsetcites.fr`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      - coolify

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
      target: runner
    container_name: dashboard-frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`dashboard-dtn.maisonsetcites.fr`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - coolify

networks:
  coolify:
    external: true